# Generated by Django 3.2.5 on 2021-07-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='post title')),
                ('text', models.TextField(verbose_name='post text')),
                ('preview', models.ImageField(upload_to='posts_previews', verbose_name='post image')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='post publication date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post author')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ('-pub_date', 'title'),
            },
        ),
    ]
