# Generated by Django 3.2.5 on 2021-08-06 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shop/products_previews', verbose_name='product image')),
                ('title', models.CharField(max_length=255, verbose_name='product title')),
                ('short_description', models.CharField(max_length=255, verbose_name='product short description')),
                ('description', models.TextField(verbose_name='product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('amount', models.PositiveIntegerField(verbose_name='product amount')),
                ('available', models.BooleanField(default=True, verbose_name='is product available')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('available', '-amount', '-price'),
            },
        ),
    ]
