# Generated by Django 3.2.5 on 2021-08-14 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='customer first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='customer last name')),
                ('address', models.CharField(max_length=255, verbose_name='customer address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='customer postal code')),
                ('city', models.CharField(max_length=100, verbose_name='customer city')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('viewed', 'viewed'), ('sent', 'sent'), ('arrived', 'arrived')], default='processing', max_length=15, verbose_name='order status')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer user')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-pub_date', 'status'),
            },
        ),
    ]
